/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Firestore } from "firebase/firestore";
import { Auth } from "firebase/auth";
import { AuthService } from "@fireenjin/sdk";
export namespace Components {
    interface AppAdmin {
        "auth": Auth;
        "db": Firestore;
    }
    interface AppDetail {
    }
    interface AppHome {
        "auth": Auth;
        "db": Firestore;
    }
    interface AppList {
    }
    interface AppProfile {
        "auth": AuthService;
        "userId": string;
    }
    interface AppTournament {
        "db": Firestore;
        "tournamentId": string;
    }
    interface AppTournamentList {
    }
    interface DbdgroupRouter {
    }
    interface ModalLogin {
    }
    interface TempTemp {
    }
}
declare global {
    interface HTMLAppAdminElement extends Components.AppAdmin, HTMLStencilElement {
    }
    var HTMLAppAdminElement: {
        prototype: HTMLAppAdminElement;
        new (): HTMLAppAdminElement;
    };
    interface HTMLAppDetailElement extends Components.AppDetail, HTMLStencilElement {
    }
    var HTMLAppDetailElement: {
        prototype: HTMLAppDetailElement;
        new (): HTMLAppDetailElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppListElement extends Components.AppList, HTMLStencilElement {
    }
    var HTMLAppListElement: {
        prototype: HTMLAppListElement;
        new (): HTMLAppListElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppTournamentElement extends Components.AppTournament, HTMLStencilElement {
    }
    var HTMLAppTournamentElement: {
        prototype: HTMLAppTournamentElement;
        new (): HTMLAppTournamentElement;
    };
    interface HTMLAppTournamentListElement extends Components.AppTournamentList, HTMLStencilElement {
    }
    var HTMLAppTournamentListElement: {
        prototype: HTMLAppTournamentListElement;
        new (): HTMLAppTournamentListElement;
    };
    interface HTMLDbdgroupRouterElement extends Components.DbdgroupRouter, HTMLStencilElement {
    }
    var HTMLDbdgroupRouterElement: {
        prototype: HTMLDbdgroupRouterElement;
        new (): HTMLDbdgroupRouterElement;
    };
    interface HTMLModalLoginElement extends Components.ModalLogin, HTMLStencilElement {
    }
    var HTMLModalLoginElement: {
        prototype: HTMLModalLoginElement;
        new (): HTMLModalLoginElement;
    };
    interface HTMLTempTempElement extends Components.TempTemp, HTMLStencilElement {
    }
    var HTMLTempTempElement: {
        prototype: HTMLTempTempElement;
        new (): HTMLTempTempElement;
    };
    interface HTMLElementTagNameMap {
        "app-admin": HTMLAppAdminElement;
        "app-detail": HTMLAppDetailElement;
        "app-home": HTMLAppHomeElement;
        "app-list": HTMLAppListElement;
        "app-profile": HTMLAppProfileElement;
        "app-tournament": HTMLAppTournamentElement;
        "app-tournament-list": HTMLAppTournamentListElement;
        "dbdgroup-router": HTMLDbdgroupRouterElement;
        "modal-login": HTMLModalLoginElement;
        "temp-temp": HTMLTempTempElement;
    }
}
declare namespace LocalJSX {
    interface AppAdmin {
        "auth"?: Auth;
        "db"?: Firestore;
    }
    interface AppDetail {
    }
    interface AppHome {
        "auth"?: Auth;
        "db"?: Firestore;
        "onDbdModalOpen"?: (event: CustomEvent<{
    component: string;
    componentProps?: any;
    cssClass?: string;
  }>) => void;
    }
    interface AppList {
    }
    interface AppProfile {
        "auth"?: AuthService;
        "userId"?: string;
    }
    interface AppTournament {
        "db"?: Firestore;
        "tournamentId"?: string;
    }
    interface AppTournamentList {
    }
    interface DbdgroupRouter {
    }
    interface ModalLogin {
    }
    interface TempTemp {
    }
    interface IntrinsicElements {
        "app-admin": AppAdmin;
        "app-detail": AppDetail;
        "app-home": AppHome;
        "app-list": AppList;
        "app-profile": AppProfile;
        "app-tournament": AppTournament;
        "app-tournament-list": AppTournamentList;
        "dbdgroup-router": DbdgroupRouter;
        "modal-login": ModalLogin;
        "temp-temp": TempTemp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-admin": LocalJSX.AppAdmin & JSXBase.HTMLAttributes<HTMLAppAdminElement>;
            "app-detail": LocalJSX.AppDetail & JSXBase.HTMLAttributes<HTMLAppDetailElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-list": LocalJSX.AppList & JSXBase.HTMLAttributes<HTMLAppListElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-tournament": LocalJSX.AppTournament & JSXBase.HTMLAttributes<HTMLAppTournamentElement>;
            "app-tournament-list": LocalJSX.AppTournamentList & JSXBase.HTMLAttributes<HTMLAppTournamentListElement>;
            "dbdgroup-router": LocalJSX.DbdgroupRouter & JSXBase.HTMLAttributes<HTMLDbdgroupRouterElement>;
            "modal-login": LocalJSX.ModalLogin & JSXBase.HTMLAttributes<HTMLModalLoginElement>;
            "temp-temp": LocalJSX.TempTemp & JSXBase.HTMLAttributes<HTMLTempTempElement>;
        }
    }
}
